version: '3'
services:
  web:
    build: .
    image: netty-image
    ports:
      - "80:8080"
    working_dir: /app/client
    command: ['yarn', 'serve']
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app
  api:
    build: .
    image: netty-image
    ports:
      - "5000:5000"
    working_dir: /app/server
    command: ['./run.sh']
    links:
      - mongodb
    restart: always
    volumes:
      - /etc/localtime:/etc/localtime:ro
      - .:/app
  mongodb:
    image: mongo
    restart: always
    volumes:
      - ../deployment/mongodb/data/db:/data/db
      - /etc/localtime:/etc/localtime:ro
    ports:
      - "27017:27017"
    
